### PR TITLE
Net452

### PR DESCRIPTION
**Pull request by DamianReeves**
#10 Downgrade to .NET 4.5.2

### CODE REVIEW

**Comment by nvivo** [comment]
Thanks @DamianReeves. Just one thing: I don't think the readonlylinkedlist is related to the downgrade. Also, it shouldn't be needed because the instance that is passed is replaced after being handed over,  and also the method that receives it accepts an ienumerable,  so it's readonly by contract.

Can you please just remove this change? Thanks.

**Comment by DamianReeves** [comment]
It's strange, despite what the documentation says, the compiler is complains that `LinkedList<T>` does not implement `IReadOnlyCollection<T>` when I downgrade to .NET 4.5.2. That is why I included that particular change.

Also I don't see where you are referring to the instance that is passed being replaced. I see the assignment passing through [as is](https://github.com/DamianReeves/Even/blob/net452/Src/Even/Utils/BatchStringBuilder.cs#L123). 

The `items` field is assigned to the `appended` variable and then `appended` is passed through and used directly in the constructor [down below](https://github.com/DamianReeves/Even/blob/net452/Src/Even/Utils/BatchStringBuilder.cs#L150), and is then directly [assigned to the `Items` property](https://github.com/DamianReeves/Even/blob/net452/Src/Even/Utils/BatchStringBuilder.cs#L152).

**Comment by nvivo** [comment]
Right, looks like the documentation on MSDN is not exactly right for this. I'm merging this as this sounds like a good solution without additional changes.

Just to clarify what I meant, if you look at the [next lines](https://github.com/DamianReeves/Even/blob/net452/Src/Even/Utils/BatchStringBuilder.cs#L123-L126), the `items` instance is replaced by a new linked list before returning the output, so it doesn't really matter what happens to it.

Sorry for being picky, I'm just trying to avoid adding helpers for things that may already be on .NET. Maybe I'll just change the signature of the output class to use a List directly. It's an internal class anyway, shouldn't hurt.

**Comment by DamianReeves** [comment]
Thanks. Look forward to many more contributions

**Pull request merged**
